### ISSUE TITLE
Longhaul Test UI and alerts

### ISSUE THREAD

**Issue by msfussell** [dapr/test-infra#83] opened 2020-11-19 18:53 UTC
To promote visibility for both maintainers and users, we need to expose a UI (Web UI?) that shows the results for scheduled Long tests for given release.

In addition, in order to detect we need to come up with the means of comparing between the results of the currently running Long haul test and the results of the prior test and alert maintainers if there's a regression.

**Comment by msfussell** [comment] 2020-11-19 18:56
See issue #17

**Comment by wcs1only** [comment] 2020-12-04 21:53
Dupe of https://github.com/dapr/test-infra/issues/73

**Closed by wcs1only** 2020-12-04 21:53 UTC
Labels: area/test/longhaul
